version: '3.8'
name: rinha-de-backend
services:
  
  pgadmin-server:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: localhost@localhost.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "4300:80"
    networks:
      - rinha-net-php

networks:
  rinha-net-php:
    driver: bridge
    external: true
    name: rinha-net-php