version: '3.8'
name: rinha-de-backend-php
services:

  app1: &app
    container_name: app1
    build:
      context: ./api
      dockerfile: ./dockerfile-dev
    depends_on:
      - postgres
    network_mode: host
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=password
      - DB_NAME=rinha
    volumes:
      - ./api/app:/var/www/html/public
      - ./api/php.ini:/usr/local/etc/php/php.ini
      - ./api/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./api/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./api/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "100MB"

  app2:
    <<: *app
    container_name: app2
    volumes:
      - ./api/app:/var/www/html/public
      - ./api/php.ini:/usr/local/etc/php/php.ini
      - ./api/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./api/www2.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./api/zz-docker2.conf:/usr/local/etc/php-fpm.d/zz-docker.conf

  nginx:
    container_name: nginx-proxy
    image: nginx:latest
    volumes:
      - ./nginx-proxy-mode-host.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    network_mode: host
    expose: 
      - 9999
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "40MB"

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:latest
    command: postgres -c 'max_connections=64'
    network_mode: host
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rinha
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: "310MB"
