FROM php:8.3-fpm-alpine

# Install JSON OPCache PDO PDO_PGSQL extensions
RUN apk add --no-cache postgresql-dev \
    && docker-php-ext-install pdo_pgsql opcache

# disable access.log
RUN sed -i 's/access.log/;access.log/g' /usr/local/etc/php-fpm.d/docker.conf

# copy the php.ini configuration
COPY ./php.ini /usr/local/etc/php/php.ini
# copy the php-fpm configuration
COPY ./php-fpm.conf /usr/local/etc/php-fpm.conf
COPY ./www.conf /usr/local/etc/php-fpm.d/www.conf

# copy app
COPY ./app /var/www/html/public